tasks:
  - init: npm install
    command: |
      gp sync-await 3306
      npm run dev
    name: run app
  - init: docker-compose -f .gitpod/docker-compose.yml pull
    command: docker-compose -f .gitpod/docker-compose.yml -d up && gp sync-done 3306
    name: run mysql

image:
  file: .gitpod.Dockerfile

github:
  prebuilds:
    addBadge: true
    master: true
    branches: true
    pullRequests: true